workspace(name = "smoke_test_remote_graalvm_repository")

# CONFIGURE `@dwtj_rules_java` ################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../../..",
)

load(
    "@dwtj_rules_java//graalvm:repositories.bzl",
    "local_graalvm_repository",
)
load(
    "@dwtj_rules_java//test/workspaces:external_repositories.bzl",
    "remote_graalvm_linux_x64",
)

# CONFIGURE `@remote_graalvm_linux_x64` #######################################

remote_graalvm_linux_x64()

load("@remote_graalvm_linux_x64//:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@local_graalvm` ###################################################

# TODO(dwtj): Remove this use of `local_graalvm_repository` once
#  `register_graalvm_toolchains` is supported by `remote_graalvm_repository`.

local_graalvm_repository(
    name = "local_graalvm",
)

load("@local_graalvm//graalvm:defs.bzl", "register_graalvm_toolchains")

register_graalvm_toolchains()
