workspace(name = "smoke_test_openjdk_source_repositories")

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

load("@dwtj_rules_java//java:repositories.bzl", "remote_openjdk_source_repository")

remote_openjdk_source_repository(
    name = "jdk_16_21",
    url = "https://github.com/openjdk/jdk/archive/jdk-16+21.tar.gz",
    sha256 = "c3d2fa52e400099b22e7c2f901c3c21d888bf2b227dce9d44174a7e97a1dfb33",
    strip_prefix = "jdk-jdk-16-21"
)

load("@jdk_16_21//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()
