workspace(name = "example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# CONFIGURE `@dwtj_rules_java` #################################################

DWTJ_RULES_JAVA_ARCHIVE_INFO = {
    "commit": "c98b7a20eb0e72a72abeb9f395ae1da0ebd10eff",
    "sha256": "868bf3b376745d17474554ba7061da41cd23cda5ef080fe6f4792453575ed026",
}
http_archive(
    name = "dwtj_rules_java",
    url = "https://github.com/dwtj/dwtj_rules_java/archive/{}.zip".format(DWTJ_RULES_JAVA_ARCHIVE_INFO["commit"]),
    strip_prefix = "dwtj_rules_java-{}".format(DWTJ_RULES_JAVA_ARCHIVE_INFO["commit"]),
    sha256 = DWTJ_RULES_JAVA_ARCHIVE_INFO["sha256"],
)

# CONFIGURE A `@local_openjdk_repository` ######################################

load("@dwtj_rules_java//java:repositories.bzl", "dwtj_local_openjdk_repository")

dwtj_local_openjdk_repository(
    name = "dwtj_local_openjdk",
)

load("@dwtj_local_openjdk//:defs.bzl", "register_java_toolchains")

register_java_toolchains()
