workspace(name = "example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# CONFIGURE `@dwtj_rules_java` #################################################

DWTJ_RULES_JAVA_ARCHIVE_INFO = {
    "commit": "5d57355344dd4763f82f500011e2b4925f7ea8f1",
    "sha256": "a819b0c567b72f4f5960391c3a8111592c91dd94ae86b45d2c7fb7b9243143b2",
}
http_archive(
    name = "dwtj_rules_java",
    url = "https://github.com/dwtj/dwtj_rules_java/archive/{}.zip".format(DWTJ_RULES_JAVA_ARCHIVE_INFO["commit"]),
    strip_prefix = "dwtj_rules_java-{}".format(DWTJ_RULES_JAVA_ARCHIVE_INFO["commit"]),
    sha256 = DWTJ_RULES_JAVA_ARCHIVE_INFO["sha256"],
)

# CONFIGURE A `@local_openjdk_repository` ######################################

load("@dwtj_rules_java//java:repositories.bzl", "dwtj_local_openjdk_repository")

dwtj_local_openjdk_repository(
    name = "dwtj_local_openjdk",
)

load("@dwtj_local_openjdk//:defs.bzl", "register_java_toolchains")

register_java_toolchains()
