load("@dwtj_rules_java//java:defs.bzl", java_library = "dwtj_java_library")

java_library(
    name = "WellFormatted",
    srcs = ["src/WellFormatted.java"],
)

java_library(
    name = "BadlyFormatted",
    srcs = ["src/BadlyFormatted.java"],
) 
