workspace(name = "smoke_test_google_java_format_aspect")

# CONFIGURE `@dwtj_rules_java` #################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

load(
    "@dwtj_rules_java//java:repositories.bzl",
    "dwtj_local_openjdk_repository",
    "remote_google_java_format_repository"
)

# CONFIGURE `@dwtj_local_openjdk` ##############################################

dwtj_local_openjdk_repository(
    name = "dwtj_local_openjdk",
)

load("@dwtj_local_openjdk//:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@google_java_format` ##############################################

remote_google_java_format_repository(
    name = 'google_java_format',
)

load('@google_java_format//:defs.bzl', 'register_google_java_format_toolchain')

register_google_java_format_toolchain()
