/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_MyLib */

#ifndef _Included_jni_MyLib
#define _Included_jni_MyLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_MyLib
 * Method:    myMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_MyLib_myMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
