workspace(name = "smoke_test_error_prone_aspect")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# CONFIGURE `@dwtj_rules_java` #################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

load(
    "@dwtj_rules_java//java:repositories.bzl",
    "dwtj_local_openjdk_repository",
    "maven_error_prone_repository",
)

load(
    "@dwtj_rules_java//test/workspaces:external_repositories.bzl",
    "rules_jvm_external",
)

# CONFIGURE `@dwtj_local_openjdk` ##############################################

dwtj_local_openjdk_repository(
    name = "dwtj_local_openjdk",
)

load("@dwtj_local_openjdk//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@rules_jvm_external` ##############################################
# NOTE(dwtj): These rules are a prerequisite of `maven_error_prone_repository`.

rules_jvm_external()

# CONFIGURE `@error_prone` #####################################################

maven_error_prone_repository(
    name = "error_prone",
)

load(
    "@error_prone//:defs.bzl",
    "fetch_error_prone_toolchain",
    "register_error_prone_toolchain",
)

fetch_error_prone_toolchain()
register_error_prone_toolchain()
