workspace(name = "smoke_test_error_prone_aspect")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# CONFIGURE `@dwtj_rules_java` #################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

load(
    "@dwtj_rules_java//java:repositories.bzl",
    "dwtj_local_openjdk_repository",
    "maven_error_prone_repository",
)

# CONFIGURE `@dwtj_local_openjdk` ##############################################

dwtj_local_openjdk_repository(
    name = "dwtj_local_openjdk",
)

load("@dwtj_local_openjdk//:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@rules_jvm_external` ##############################################

# NOTE(dwtj): These rules are a prerequisite of `maven_error_prone_repository`.

# NOTE(dwtj): This version was used just because it was the latest release as of
#  2020-07-28.
RULES_JVM_EXTERNAL_ARCHIVE_INFO = {
    "tag": "3.3",
    "sha256": "d85951a92c0908c80bd8551002d66cb23c3434409c814179c0ff026b53544dab",
}

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_ARCHIVE_INFO["tag"],
    sha256 = RULES_JVM_EXTERNAL_ARCHIVE_INFO["sha256"],
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_ARCHIVE_INFO["tag"],
)

# CONFIGURE `@error_prone` #####################################################

maven_error_prone_repository(
    name = "error_prone",
)

load(
    "@error_prone//:defs.bzl",
    "fetch_error_prone_toolchain",
    "register_error_prone_toolchain",
)

fetch_error_prone_toolchain()
register_error_prone_toolchain()
