workspace(name = "smoke_test_graalvm_native_image_resources")

# CONFIGURE `@dwtj_rules_java` ################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../../..",
)

load(
    "@dwtj_rules_java//test/workspaces:external_repositories.bzl",
    "remote_graalvm_linux_x64",
)

# CONFIGURE `@remote_graalvm_linux_x64` #######################################

remote_graalvm_linux_x64()

load("@remote_graalvm_linux_x64//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()

load("@remote_graalvm_linux_x64//graalvm:defs.bzl", "register_graalvm_toolchains")

register_graalvm_toolchains()
