workspace(name = "smoke_test_toolchain_overrides")

# CONFIGURE `@dwtj_rules_java` ################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

load(
    "@dwtj_rules_java//java:repositories.bzl",
    "maven_error_prone_repository",
)

load(
    "@dwtj_rules_java//test/workspaces:external_repositories.bzl",
    "remote_openjdk_linux_x64",
    "remote_graalvm_linux_x64",
    "remote_openjdk_macos_x64",
    "remote_graalvm_macos_x64",
    "rules_jvm_external",
)

# CONFIGURE `@remote_openjdk_linux_x64` ##################################

remote_openjdk_linux_x64()

load("@remote_openjdk_linux_x64//java:defs.bzl", register_linux_java_toolchains = "register_java_toolchains")

register_linux_java_toolchains()

# CONFIGURE `@remote_openjdk_macos_x64` ##################################

remote_openjdk_macos_x64()

load("@remote_openjdk_macos_x64//java:defs.bzl", register_macos_java_toolchains = "register_java_toolchains")

register_macos_java_toolchains()

# CONFIGURE `@remote_graalvm_linux_x64` #######################################

remote_graalvm_linux_x64()

# CONFIGURE `@remote_graalvm_macos_x64` #######################################

remote_graalvm_macos_x64()

# CONFIGURE `@rules_jvm_external` #############################################
# NOTE(dwtj): These rules are a prerequisite of `maven_error_prone_repository`.

rules_jvm_external()

# CONFIGURE `@error_prone` #####################################################
# NOTE(dwtj): We enable Error Prone aspect to check that it is using the
#  `java_compiler_toolchain` override attribute on the Java target (if there
#  is such an attribute).

maven_error_prone_repository(
    name = "error_prone",
)

load(
    "@error_prone//:defs.bzl",
    "fetch_error_prone_toolchain",
    "register_error_prone_toolchain",
)

fetch_error_prone_toolchain()
register_error_prone_toolchain()
