workspace(name = "smoke_test_toolchain_overrides")

# CONFIGURE `@dwtj_rules_java` ################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

load(
    "@dwtj_rules_java//test/workspaces:external_repositories.bzl",
    "adoptopenjdk_linux_v11_0_8_10",
    "remote_graalvm_linux_x64",
)

# CONFIGURE `@adoptopenjdk_linux_v11_0_8_10` ##################################

# TODO(dwtj): Figure out how to make this test workspace more portable.
#  (E.g., make this test runnable on macOS or different CPU architectures).

adoptopenjdk_linux_v11_0_8_10()

load("@adoptopenjdk_linux_v11_0_8_10//:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@remote_graalvm_linux_x64` #######################################

remote_graalvm_linux_x64()
