workspace(name = "smoke_test_openjdk_source_repositories")

local_repository(
    name = "dwtj_rules_java",
    path = "../../../..",
)

load("@dwtj_rules_java//experimental/java:repositories.bzl", "remote_openjdk_source_repository")

remote_openjdk_source_repository(
    name = "jdk_15_ga",
    url = "https://github.com/openjdk/jdk/archive/jdk-15-ga.tar.gz",
    sha256 = "f86e3828e5e5988fb555a9f6c7b84603fb819bd05a381f241860205af309d812",
    strip_prefix = "jdk-jdk-15-ga",
    os = "linux",
)

load("@jdk_15_ga//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()
