exports_files([
    "aspects/google_java_format_aspect/TEMPLATE.run_google_java_format.sh",
    "aspects/javadoc_aspect/TEMPLATE.run_javadoc.sh",
    "rules/common/actions/TEMPLATE.compile_and_jar_java_sources.sh",
    "rules/common/actions/TEMPLATE.java_run_script.sh",
])