'''Defines the `java_library` rule.
'''

load("//java:providers/JavaCompilationInfo.bzl", "JavaCompilationInfo")
load("//java:providers/JavaDependencyInfo.bzl", "JavaDependencyInfo")

load("//java:toolchain_rules/java_compiler_toolchain.bzl", "JavaCompilerToolchainInfo")

load("//java:common/actions/compile_and_jar_java_sources.bzl", "compile_and_jar_java_target")

load(
    "//java:common/providers.bzl",
    "singleton_java_dependency_info",
    "make_legacy_java_info",
)

def _java_library_impl(ctx):
    java_compilation_info = compile_and_jar_java_target(ctx)
    output_jar = java_compilation_info.class_files_output_jar

    return [
        DefaultInfo(files = depset(direct = [output_jar])),
        java_compilation_info,
        singleton_java_dependency_info(output_jar),
        make_legacy_java_info(java_compilation_info, ctx.attr.deps),
    ]

java_library = rule(
    implementation = _java_library_impl,
    attrs = {
        "srcs": attr.label_list(
            # TODO(dwtj): Consider supporting empty `srcs` list once `exports`
            #  is supported.
            allow_empty = False,
            doc = "A list of Java source files whose derived class files should be included in this library (and any of its dependents).",
            allow_files = [".java"],
            default = list(),
        ),
        "deps": attr.label_list(
            providers = [
                JavaDependencyInfo,
                JavaInfo,
            ],
            default = list(),
        ),
        "additional_jar_manifest_attributes": attr.string_list(
            doc = "A list of strings; each will be added as a line of the output JAR's manifest file.",
            default = list(),
        ),
        "output_jar": attr.output(
            doc = "The name of the JAR file generated by this target. This JAR contains the class files generated by this target's Java compiler invocation.",
        ),
        "java_compiler_toolchain": attr.label(
            doc = "This optional attribute can override the global Java compiler toolchain. This expects a label for a `java_compiler_toolchain` target (or more precisely, a target providing `JavaCompilerToolchainInfo`).",
            providers = [JavaCompilerToolchainInfo],
        ),
    },
    provides = [
        JavaCompilationInfo,
        JavaDependencyInfo,
        JavaInfo,
    ],
    toolchains = [
        "@dwtj_rules_java//java/toolchains/java_compiler_toolchain:toolchain_type",
    ],
)
