workspace(name = "smoke_test_graalvm_native_image_rules")

# CONFIGURE `@dwtj_rules_java` #################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../../..",
)

load(
    "@dwtj_rules_java//graalvm:repositories.bzl",
    "local_graalvm_repository",
)

load(
    "@dwtj_rules_java//test/workspaces:external_repositories.bzl",
    "remote_graalvm_linux_x64",
)

# CONFIGURE `@remote_graalvm_linux_x64` #######################################

# TODO(dwtj): Figure out how to make this test workspace more portable.
#  (E.g., make this test runnable on macOS or different CPU architectures).
remote_graalvm_linux_x64()

load("@remote_graalvm_linux_x64//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@local_graalvm` ###################################################

local_graalvm_repository(
    name = "local_graalvm",
)

load("@local_graalvm//graalvm:defs.bzl", "register_graalvm_toolchains")

register_graalvm_toolchains()
