#!/bin/sh -
#
# This script was generated from a template with the following substitutions:
# 
# - JAVAC_EXECUTABLE: {JAVAC_EXECUTABLE}
# - CLASS_OUTPUT_DIRECTORY: {CLASS_OUTPUT_DIRECTORY}
# - CLASS_PATH_ARGS_FILE: {CLASS_PATH_ARGS_FILE}
# - JAVAC_ARGUMENTS_FILE: {JAVAC_ARGUMENTS_FILE}
# - JAR_EXECUTABLE: {JAR_EXECUTABLE}
# - JAR_MANIFEST_FILE: {JAR_MANIFEST_FILE}
# - OUTPUT_JAR: {OUTPUT_JAR}

set -e

"{JAVAC_EXECUTABLE}" -d "{CLASS_OUTPUT_DIRECTORY}" "@{CLASS_PATH_ARGS_FILE}" "@{JAVAC_ARGUMENTS_FILE}"
"{JAR_EXECUTABLE}" --create "--file={OUTPUT_JAR}" "--manifest={JAR_MANIFEST_FILE}" -C "{CLASS_OUTPUT_DIRECTORY}" .