workspace(name = "smoke_test_remote_openjdk_repository")

# CONFIGURE `@dwtj_rules_java` #################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

load(
    "@dwtj_rules_java//test/workspaces:external_repositories.bzl",
    "remote_openjdk_linux_x64",
    "remote_openjdk_macos_x64",
    "rules_cc",
    "rules_rust",
    "platforms",
)

# CONFIGURE `@platforms` #######################################################

platforms()

# CONFIGURE JAVA TOOLCHAINS ####################################################

remote_openjdk_linux_x64()

load("@remote_openjdk_linux_x64//java:defs.bzl", register_linux_java_toolchains = "register_java_toolchains")

register_linux_java_toolchains()

remote_openjdk_macos_x64()

load("@remote_openjdk_macos_x64//java:defs.bzl", register_macos_java_toolchains = "register_java_toolchains")

register_macos_java_toolchains()

# CONFIGURE `@rules_cc` ########################################################

rules_cc()

# CONFIGURE `@rules_rust` ######################################################

rules_rust()

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()

load("@io_bazel_rules_rust//:workspace.bzl", "rust_workspace")

rust_workspace()
