load("@dwtj_rules_java//java:defs.bzl", "dwtj_java_binary")

dwtj_java_binary(
    name = "MyTestBin",
    main_class = "st.java.MyTestBin",
    srcs = ["MyTestBin.java"],
    visibility = ["//visibility:public"],
)
