workspace(name = "smoke_test_graalvm_native_image_rule")

# CONFIGURE `@dwtj_rules_java` #################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../../..",
)

load(
    "@dwtj_rules_java//graalvm:repositories.bzl",
    "local_graalvm_repository",
)

# CONFIGURE JAVA TOOLCHAINS ####################################################

# TODO(dwtj): Figure out how to make this test workspace more portable.
#  (E.g., make this test runnable on macOS or different CPU architectures).
load(
    "@dwtj_rules_java//test/workspaces:external_repositories.bzl",
    "adoptopenjdk_linux_v11_0_8_10",
)

adoptopenjdk_linux_v11_0_8_10()

load("@adoptopenjdk_linux_v11_0_8_10//:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE `@local_graalvm` ###################################################

local_graalvm_repository(
    name = "local_graalvm",
)

load("@local_graalvm//:defs.bzl", "register_graalvm_toolchains")

register_graalvm_toolchains()
