workspace(name = "smoke_test_transitive_dependencies")

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

load(
    "@dwtj_rules_java//java:repositories.bzl",
    "dwtj_local_openjdk_repository",
)

dwtj_local_openjdk_repository(
    name = "dwtj_local_openjdk",
)

load("@dwtj_local_openjdk//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()
