load("@dwtj_rules_java//java:defs.bzl", "dwtj_java_library")

dwtj_java_library(
    name = "GoodJavadoc",
    srcs = ["GoodJavadoc.java"],
)

dwtj_java_library(
    name = "BadJavadoc",
    srcs = ["BadJavadoc.java"],
)