workspace(name = "smoke_test_known_openjdk_repository_macro")

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

load("@dwtj_rules_java//java:repositories.bzl", "known_openjdk_repository")

# CONFIGURE `@default_linux_openjdk` ##########################################

known_openjdk_repository(name = "default_linux_openjdk")

load("@default_linux_openjdk//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()

# CONFIGURE OTHER KNOWN OPENJDK REPOSITORIES ##################################

known_openjdk_repository(
    name = "jdk_java_net_linux_jdk_14_0_2",
    provider = "jdk_java_net",
    os = "linux",
    version = "14.0.2",
)

known_openjdk_repository(
    name = "adoptopenjdk_upstream_linux_jdk_11_0_9_11",
    provider = "adoptopenjdk_upstream",
    os = "linux",
    version = "11.0.9+11",
)

known_openjdk_repository(
    name = "adoptopenjdk_linux_jdk_11_0_9_11",
    provider = "adoptopenjdk",
    os = "linux",
    version = "11.0.9+11.1"
)


# TODO(dwtj): Re-enable this once I fix the crashes.
# known_openjdk_repository(
#     name = "adoptopenjdk_linux_jdk_11_0_9_11_openj9_0_23_0",
#     provider = "adoptopenjdk",
#     jvm = "openj9",
#     os = "linux",
#     version = "11.0.9+11_openj9-0.23.0"
# )
