load("@dwtj_rules_java//java:defs.bzl", "dwtj_java_library")

dwtj_java_library(
    name = "GoodJava",
    srcs = ["mypkg/GoodJava.java"],
)

dwtj_java_library(
    name = "WarningJava",
    srcs = ["mypkg/WarningJava.java"],
)
