workspace(name = "website")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# CONFIGURE `@dwtj_rules_java` #################################################

local_repository(
    name = "dwtj_rules_java",
    path = "..",
)

# CONFIGURE `@io_bazel_stardoc` ################################################
#
# This dependency is used to compile `.bzl` files to markdown for use as
# documentation.
#
# NOTE(dwtj): We use this version of these rules because it is the latest
#  release as of 2020-09-17.

_STARDOC_TAG = "0.4.0"
_STARDOC_SHA256 = "6d07d18c15abb0f6d393adbd6075cd661a2219faab56a9517741f0fc755f6f3c"

http_archive(
    name = "io_bazel_stardoc",
    url = "https://github.com/bazelbuild/stardoc/archive/{}.tar.gz".format(_STARDOC_TAG),
    sha256 = _STARDOC_SHA256,
    strip_prefix = "stardoc-{}".format(_STARDOC_TAG),
)

load("@io_bazel_stardoc//:setup.bzl", "stardoc_repositories")
stardoc_repositories()

# CONFIGURE `@rules_pkg` #######################################################
#
# This dependency is used to archive the website as a tarball.
#
# NOTE(dwtj): We use this version of these rules because it is the latest
#  release as of 2020-09-01.

_RULES_PKG_TAG = "0.2.5"
_RULES_PKG_SHA256 = "352c090cc3d3f9a6b4e676cf42a6047c16824959b438895a76c2989c6d7c246a"

http_archive(
    name = "rules_pkg",
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/{0}/rules_pkg-{0}.tar.gz".format(_RULES_PKG_TAG),
    sha256 = _RULES_PKG_SHA256,
)
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()

# CONFIGURE `@dwtj_rules_hugo` #################################################
#
# This dependency is used to compile website build assets into a deployable
# website.
#
# NOTE(dwtj): We use this version of these rules because it is the latest
#  release as of 2020-09-17.

DWTJ_RULES_HUGO_SHA256 = "97c05c2665e7cfcadd8215ff26dbaa88d487c94e6a0c5d9f5c37f368b7126791"
DWTJ_RULES_HUGO_COMMIT = "02eaf9946058c2a286c79d49da14a35caf574bea"

http_archive(
    name = "dwtj_rules_hugo",
    url = "https://github.com/dwtj/dwtj_rules_hugo/archive/{}.zip".format(DWTJ_RULES_HUGO_COMMIT),
    strip_prefix = "dwtj_rules_hugo-{}".format(DWTJ_RULES_HUGO_COMMIT),
    sha256 = DWTJ_RULES_HUGO_SHA256,
)

load("@dwtj_rules_hugo//hugo:repositories.bzl", "local_hugo_repository")
local_hugo_repository(name = "local_hugo")

load("@local_hugo//:defs.bzl", "register_hugo_toolchain")
register_hugo_toolchain()

# CONFIGURE `@dwtj_rules_hugo_website` #########################################
#
# This dependency includes a Hugo website template. This template is the
# foundation for our website, specifically, its structure and styling. It is
# mainly just *content* that comes from our workspace.
#
# NOTE(dwtj): This is very similar to the configuration of `@dwtj_rules_hugo`
# above: we fetch the same archive again, except here we discard everything
# but the `website/` directory. (Like in this project, the `website/` directory is
# expected to be the root of its own Bazel workspace).

http_archive(
    name = "dwtj_rules_hugo_website",
    url = "https://github.com/dwtj/dwtj_rules_hugo/archive/{}.zip".format(DWTJ_RULES_HUGO_COMMIT),
    strip_prefix = "dwtj_rules_hugo-{}/website".format(DWTJ_RULES_HUGO_COMMIT),
    sha256 = DWTJ_RULES_HUGO_SHA256,
)
