workspace(name = "smoke_test_remote_openjdk_repository")

# CONFIGURE `@dwtj_rules_java` #################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

# CONFIGURE JAVA TOOLCHAINS ####################################################

# TODO(dwtj): Figure out how to make this test workspace more portable.
#  (E.g., make this test runnable on macOS or different CPU architectures).
load(
    "@dwtj_rules_java//test/workspaces:external_repositories.bzl",
    "adoptopenjdk_linux_v11_0_8_10",
)

adoptopenjdk_linux_v11_0_8_10()

load("@adoptopenjdk_linux_v11_0_8_10//java:defs.bzl", "register_java_toolchains")

register_java_toolchains()
