workspace(name = "smoke_test_remote_openjdk_repository")

# CONFIGURE `@dwtj_rules_java` #################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

load(
    "@dwtj_rules_java//test/workspaces:external_repositories.bzl",
    "platforms",
    "remote_openjdk_linux_x64",
    "remote_openjdk_macos_x64",
)

# CONFIGURE `@platforms` #######################################################

platforms()

# CONFIGURE JAVA TOOLCHAINS ####################################################

remote_openjdk_linux_x64()

load("@remote_openjdk_linux_x64//java:defs.bzl", register_linux_java_toolchains = "register_java_toolchains")

register_linux_java_toolchains()

remote_openjdk_macos_x64()

load("@remote_openjdk_macos_x64//java:defs.bzl", register_macos_java_toolchains = "register_java_toolchains")

register_macos_java_toolchains()
