workspace(name = "smoke_test_remote_openjdk_repository")

# CONFIGURE `@dwtj_rules_java` #################################################

local_repository(
    name = "dwtj_rules_java",
    path = "../../..",
)

load(
    "@dwtj_rules_java//java:repositories.bzl",
    "dwtj_remote_openjdk_repository",
)

# CONFIGURE `@dwtj_remote_openjdk` ##############################################

# TODO(dwtj): Figure out how to make this test more portable.
dwtj_remote_openjdk_repository(
    name = "adoptopenjdk_linux_v11_0_8_10",
    url = "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.8_10.tar.gz",
    sha256 = "6e4cead158037cb7747ca47416474d4f408c9126be5b96f9befd532e0a762b47",
    strip_prefix = "jdk-11.0.8+10",
)

load("@adoptopenjdk_linux_v11_0_8_10//:defs.bzl", "register_java_toolchains")

register_java_toolchains()
